/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.fsm.client.gui;

import java.io.BufferedReader;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.PrintWriter;
import java.net.Socket;
import java.nio.charset.Charset;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.ListModel;

/**
 *
 * @author Yakup
 */
public class MainPage extends javax.swing.JFrame {
    
    private void SendMessage(String msg){
        try {
            byte[] bytes = msg.getBytes();
            this.out.write(bytes);  
        } catch (IOException err) {
            
        }
    }
    
    private String ReadMessage(){
        try {
            byte[] messageByte = new byte[1024];
            int bytesRead = this.in.read(messageByte); 
            return new String(messageByte, 0, bytesRead, Charset.forName("UTF-8")); 
        } catch (IOException err) {
            
        }
        
        return "";
    }

    private Socket client;
    private DataInputStream in;
    private DataOutputStream out;
    private String username;
    /**
     * Creates new form MainPage
     */
    public MainPage(){
        initComponents();
    }
    
    public void initialize(Socket socket, DataInputStream in, DataOutputStream out, String username){
        this.client = socket;
        this.in = in;
        this.out = out;
        this.username = username;
        usernameLabel.setText("Kullanıcı: " + username);
        getProjectData();
    }
    
    public void getProjectData(){
        try {
            SendMessage("PROJECTS$");
            String serverResponse = ReadMessage();
            
            if(serverResponse.equals("")){
                return;
            }
            
            System.out.println(serverResponse);
            String[] projectsSplitted = serverResponse.split("\\$");
            
            DefaultListModel<String> listModel = new DefaultListModel<>(); 
           
            for (String singleProject : projectsSplitted) {
                String[] partsAgain = singleProject.split("\\*"); 
                listModel.addElement(partsAgain[0]);
            }
            
            projectsList.setModel(listModel);
            
        } catch (Exception e) {
        }   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernameLabel = new javax.swing.JLabel();
        myProjectsLabel = new javax.swing.JLabel();
        otherProjectsLabel = new javax.swing.JLabel();
        createProjectBtn = new javax.swing.JButton();
        joinProjectBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        projectsList = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        usernameLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        usernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usernameLabel.setText("Dummy Data");

        myProjectsLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        myProjectsLabel.setText("Projelerim:");

        otherProjectsLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        otherProjectsLabel.setText("Katıldığım Projeler:");

        createProjectBtn.setText("Proje Oluştur");
        createProjectBtn.setToolTipText("");
        createProjectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createProjectBtnActionPerformed(evt);
            }
        });

        joinProjectBtn.setText("Projeye Gir");
        joinProjectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joinProjectBtnActionPerformed(evt);
            }
        });

        exitBtn.setText("Çıkış YAP");
        exitBtn.setToolTipText("");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(projectsList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(usernameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(myProjectsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 187, Short.MAX_VALUE)
                        .addComponent(otherProjectsLabel)
                        .addGap(76, 76, 76))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(exitBtn)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(createProjectBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(joinProjectBtn))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(usernameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(myProjectsLabel)
                    .addComponent(otherProjectsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createProjectBtn)
                    .addComponent(joinProjectBtn)
                    .addComponent(exitBtn))
                .addGap(27, 27, 27))
        );

        usernameLabel.getAccessibleContext().setAccessibleName("usernameLabel");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        DisconnectUser();
        RouteToLoginPage();
    }//GEN-LAST:event_exitBtnActionPerformed

    private void DisconnectUser(){
        try {
            SendMessage("EXIT$");
            
            this.client.close();
            this.in.close();
            this.out.close();
            
        } catch(IOException err){
        }
    }
    
    private void RouteToLoginPage(){      
        LoginPage loginPage = new LoginPage();
        loginPage.setVisible(true);
                
        this.dispose();
    }
    
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        DisconnectUser();
    }//GEN-LAST:event_formWindowClosing

    private void joinProjectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joinProjectBtnActionPerformed
        SendMessage("CONNECT$" + username + "$A");
        String res = ReadMessage();
        
        String[] parts = res.split("\\$");
        
        String key = parts[1];
        
        ProjectPage projectPage = new ProjectPage();
        projectPage.initialize(key, client, in, out);
        projectPage.setVisible(true);
    }//GEN-LAST:event_joinProjectBtnActionPerformed

    private void createProjectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createProjectBtnActionPerformed
        CreateProjectPage createProjectPage = new CreateProjectPage();
        createProjectPage.initialize(this, client, in, out, username);
        createProjectPage.setVisible(true);
        createProjectPage.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_createProjectBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createProjectBtn;
    private javax.swing.JButton exitBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton joinProjectBtn;
    private javax.swing.JLabel myProjectsLabel;
    private javax.swing.JLabel otherProjectsLabel;
    private javax.swing.JList<String> projectsList;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
