/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.fsm.client.gui;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.net.Socket;
import javax.swing.JLabel;

/**
 *
 * @author Yakup
 */
public class MainPage extends javax.swing.JFrame {

    private Socket client;
    private BufferedReader bufferedReader;
    private PrintWriter printWriter;
    private String username;
    /**
     * Creates new form MainPage
     */
    public MainPage(){
        initComponents();
    }
    
    public void initialize(Socket socket, BufferedReader br, PrintWriter pw, String username){
        this.client = socket;
        this.bufferedReader = br;
        this.printWriter = pw;
        this.username = username;
        usernameLabel.setText("Kullanıcı: " + username);
        getProjectData();
    }
    
    public void getProjectData(){
        try {
            printWriter.println("PROJECTS$");
            String serverResponse = bufferedReader.readLine();
            System.out.println(serverResponse);
            String[] projectsSplitted = serverResponse.split("\\$");
            
            int leftLabelX = 24, beginY = 83;
            int labelLeftWidthSize = 140;
            int labelHeight = 15;
            
            for (String singleProject : projectsSplitted) {
                String[] partsAgain = singleProject.split("\\*"); 
                JLabel nameLabel = new JLabel(partsAgain[0]);
                JLabel keyLabel = new JLabel(partsAgain[1].substring(0, partsAgain[1].length()));
                
                nameLabel.setLocation(leftLabelX, beginY);
                nameLabel.setSize(140, 15);
                
                keyLabel.setLocation(leftLabelX + labelLeftWidthSize + 5, beginY);
                keyLabel.setSize(50, 15);
                
                beginY += 17;
                
                this.add(nameLabel);
                this.add(keyLabel);
            }
            
        } catch (Exception e) {
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernameLabel = new javax.swing.JLabel();
        myProjectsLabel = new javax.swing.JLabel();
        otherProjectsLabel = new javax.swing.JLabel();
        createProjectBtn = new javax.swing.JButton();
        joinProjectBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        usernameLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        usernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usernameLabel.setText("Dummy Data");

        myProjectsLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        myProjectsLabel.setText("Projelerim:");

        otherProjectsLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        otherProjectsLabel.setText("Katıldığım Projeler:");

        createProjectBtn.setText("Proje Oluştur");
        createProjectBtn.setToolTipText("");

        joinProjectBtn.setText("Projeye Gir");

        exitBtn.setText("Çıkış YAP");
        exitBtn.setToolTipText("");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(usernameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(myProjectsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 187, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(otherProjectsLabel)
                                .addGap(76, 76, 76))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(exitBtn)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(createProjectBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(joinProjectBtn)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(usernameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(myProjectsLabel)
                    .addComponent(otherProjectsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 243, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createProjectBtn)
                    .addComponent(joinProjectBtn)
                    .addComponent(exitBtn))
                .addGap(20, 20, 20))
        );

        usernameLabel.getAccessibleContext().setAccessibleName("usernameLabel");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        DisconnectUser();
        RouteToLoginPage();
    }//GEN-LAST:event_exitBtnActionPerformed

    private void DisconnectUser(){
        try {
            printWriter.println("DISCONNECT$");
            
            this.client.close();
            this.bufferedReader.close();
            this.printWriter.close();
            
        } catch(Exception err){
            err.printStackTrace();
        }
    }
    
    private void RouteToLoginPage(){      
        LoginPage loginPage = new LoginPage();
        loginPage.setVisible(true);
                
        this.dispose();
    }
    
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        DisconnectUser();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createProjectBtn;
    private javax.swing.JButton exitBtn;
    private javax.swing.JButton joinProjectBtn;
    private javax.swing.JLabel myProjectsLabel;
    private javax.swing.JLabel otherProjectsLabel;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
