package com.fsm.client.gui;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.Socket;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Şahan
 */
public class MainPage extends javax.swing.JFrame {

    private Socket client;
    private DataInputStream in;
    private DataOutputStream out;
    private String username;

    /**
     * Creates new form MainPage
     */
    public MainPage() {
        initComponents();
        setDefaultCloseOperation(MainPage.DO_NOTHING_ON_CLOSE);
    }

    public void initialize(Socket socket, DataInputStream in, DataOutputStream out, String username) {
        this.client = socket;
        this.in = in;
        this.out = out;
        this.username = username;
        usernameLabel.setText("Kullanıcı: " + username);
        getProjectData();
    }

    public void getProjectData() {
        try {
            Communication.SendMessage("PROJECTS$", out);
            String serverResponse = Communication.ReadMessage(in);

            if (serverResponse.equals("yok")) {
                return;
            }

            String actualResponse = serverResponse.substring(3);
            String[] projectsSplitted = actualResponse.split("\\$");

            DefaultListModel<String> listModel = new DefaultListModel<>();

            for (String singleProject : projectsSplitted) {
                String[] partsAgain = singleProject.split("\\*");
                String toShow = String.format("%s | %s", partsAgain[0], partsAgain[1]);
                listModel.addElement(toShow);
            }

            projectsList.setModel(listModel);

        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernameLabel = new javax.swing.JLabel();
        myProjectsLabel = new javax.swing.JLabel();
        createProjectBtn = new javax.swing.JButton();
        joinProjectBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        projectsList = new javax.swing.JList<>();
        projectKeyTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        usernameLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        usernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usernameLabel.setText("Kullanıcı: <>");

        myProjectsLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        myProjectsLabel.setText("Projelerim:");

        createProjectBtn.setText("Proje Oluştur");
        createProjectBtn.setToolTipText("");
        createProjectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createProjectBtnActionPerformed(evt);
            }
        });

        joinProjectBtn.setText("Projeye Gir");
        joinProjectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joinProjectBtnActionPerformed(evt);
            }
        });

        exitBtn.setText("Çıkış YAP");
        exitBtn.setToolTipText("");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(projectsList);

        projectKeyTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(projectKeyTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(exitBtn)
                                    .addComponent(joinProjectBtn))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usernameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(myProjectsLabel)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(63, 63, 63)
                                        .addComponent(createProjectBtn)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(usernameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(myProjectsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(projectKeyTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(joinProjectBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createProjectBtn)
                    .addComponent(exitBtn))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        usernameLabel.getAccessibleContext().setAccessibleName("usernameLabel");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        DisconnectUser();
        RouteToLoginPage();
    }//GEN-LAST:event_exitBtnActionPerformed

    private void DisconnectUser() {
        try {
            Communication.SendMessage("EXIT$", out);

            if (in != null) {
                in.close();
            }

            if (out != null) {
                out.close();
            }

            if (client != null) {
                client.close();
            }

        } catch (IOException err) {
        }
    }

    private void RouteToLoginPage() {
        LoginPage loginPage = new LoginPage();
        loginPage.setVisible(true);

        this.dispose();
    }
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        DisconnectUser();
    }//GEN-LAST:event_formWindowClosing

    private void joinProjectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joinProjectBtnActionPerformed
        String key = projectKeyTxt.getText().trim(); // Girdinin başındaki ve sonundaki boşlukları temizle

        if (key.isEmpty()) {  // Eğer key boşsa
            // JList'teki seçili öğeyi al
            Object selectedValue = projectsList.getSelectedValue();
            if (selectedValue != null) {
                key = selectedValue.toString(); // Seçili öğeyi key olarak kullan
            } else {
                // JList'te seçili öğe yoksa uyarı göster
                JOptionPane.showMessageDialog(this, "Lütfen bir proje seçin veya proje anahtarını girin.");
                return; // İşleme devam etmeyi engelle
            }
        }

        String messageToSend = String.format("CONNECT$%s", key);
        Communication.SendMessage(messageToSend, out);
        ProjectPage projectPage = new ProjectPage();
        projectPage.initialize(key, username, in, out);
        projectPage.setVisible(true);

    }//GEN-LAST:event_joinProjectBtnActionPerformed

    private void createProjectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createProjectBtnActionPerformed
        CreateProjectPage createProjectPage = new CreateProjectPage();
        createProjectPage.initialize(this, client, in, out, username);
        createProjectPage.setVisible(true);
        createProjectPage.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_createProjectBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createProjectBtn;
    private javax.swing.JButton exitBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton joinProjectBtn;
    private javax.swing.JLabel myProjectsLabel;
    private javax.swing.JTextField projectKeyTxt;
    private javax.swing.JList<String> projectsList;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
