package com.fsm.client.gui;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileInputStream;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;


public class ProjectPage extends javax.swing.JFrame{

    private DataInputStream in;
    private DataOutputStream out;
    private String key;
    private DefaultListModel<String> model = new DefaultListModel<>();
    private String username;
    
    private volatile boolean isActive = true;
    
    /**
     * Creates new form ProjectPage
     */
    public ProjectPage() {
        initComponents();
    }
    
    public void initialize(String key, String username, DataInputStream dis, DataOutputStream dos){
        this.in = dis;
        this.out = dos;
        this.key = "A";
        this.username = username;
        this.projectKeyLabel.setText(key);
        generalList.setModel(model);
        ListenForMessage();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }
    
    public void ListenForMessage(){
        new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    while(isActive){
                    String response = Communication.ReadMessage(in);
                    
                    String[] parts = response.split("\\$");
                    String command = parts[0];
                    
                    if(command.equals("USERS")){
                        String users = parts[1];
                        activeUsersLabel.setText(users);
                    }
                    
                    if(command.equals("GENERAL")){
                        
                        // Genel Mesajlaşma için:
                        //GENERAL$MESSAGE${MESSAGE DATA}
                        
                        String type = parts[1];
                        
                        if(type.equals("MESSAGE")){
                            String message = parts[2];
                            model.add(model.getSize(), message);
                        }
                        
                        // Dosya indirmek için:
                        // GENERAL$FILE{DOSYA ADI VE EKLENTİSİ}
                        // Sonra da DATA gelecek;
                        
                        else if(type.equals("FILE")){
                            String fileName = parts[2];
                            
                            Communication.ReceiveFile(fileName, in);
                        }
   
                    }
                    
                }
                } catch (Exception e) {
                }
            }
        }).start();
    }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        projectKeyIndicatorLabel = new javax.swing.JLabel();
        projectKeyLabel = new javax.swing.JLabel();
        projectKeyIndicatorLabel1 = new javax.swing.JLabel();
        activeUsersLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        generalList = new javax.swing.JList<>();
        generalMessageFieldTxt = new javax.swing.JTextField();
        generalSendMessageBtn = new javax.swing.JButton();
        disconnectBtn = new javax.swing.JButton();
        chooseFileButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        projectKeyIndicatorLabel.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        projectKeyIndicatorLabel.setText("Proje Anahtarı:");

        projectKeyLabel.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        projectKeyLabel.setText("<>");

        projectKeyIndicatorLabel1.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        projectKeyIndicatorLabel1.setText("Aktif Kullanıcılar:");

        activeUsersLabel.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        activeUsersLabel.setText("<>");

        jLabel1.setText("Genel Mesajlaşma");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jScrollPane1.setViewportView(generalList);

        generalSendMessageBtn.setText("Genel Mesaj GÖNDER");
        generalSendMessageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generalSendMessageBtnActionPerformed(evt);
            }
        });

        disconnectBtn.setText("Projeden ÇIK");
        disconnectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disconnectBtnActionPerformed(evt);
            }
        });

        chooseFileButton.setText("Dosya SEÇ");
        chooseFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseFileButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(projectKeyIndicatorLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(projectKeyLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(projectKeyIndicatorLabel1)
                                .addGap(9, 9, 9)
                                .addComponent(activeUsersLabel))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(generalSendMessageBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chooseFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(disconnectBtn)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(generalMessageFieldTxt)
                    .addComponent(jScrollPane1))
                .addGap(229, 229, 229))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(projectKeyIndicatorLabel)
                    .addComponent(projectKeyLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(projectKeyIndicatorLabel1)
                    .addComponent(activeUsersLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(generalMessageFieldTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(generalSendMessageBtn)
                    .addComponent(chooseFileButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(disconnectBtn)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generalSendMessageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generalSendMessageBtnActionPerformed
        String messageToSend = "GENERAL$" + "A$" + generalMessageFieldTxt.getText(); // TO DO: Değişecek
        
        Communication.SendMessage(messageToSend, out);
        
        generalMessageFieldTxt.setText("");
    }//GEN-LAST:event_generalSendMessageBtnActionPerformed

    private void disconnectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disconnectBtnActionPerformed
        String messageToSend = "DISCONNECT$A";
        Communication.SendMessage(messageToSend, out);
        this.isActive = false;
        this.dispose();
    }//GEN-LAST:event_disconnectBtnActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        String messageToSend = "DISCONNECT$A";
        Communication.SendMessage(messageToSend, out);
        this.isActive = false;
    }//GEN-LAST:event_formWindowClosing
    
    private void chooseFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseFileButtonActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        
        int returnValue = fileChooser.showOpenDialog(null);
        
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            FileInputStream fin = null;
            try {
                File selectedFile = fileChooser.getSelectedFile();
                
                String fileName = selectedFile.getName();
                
                // Sunucuya dosyanın adını gönderiyorum arkaplanda halletmesi için.
                Communication.SendMessage("GENERAL$A$FILE$" + fileName, out);

                Communication.SendFile(selectedFile, out);
            }
            catch(Exception e){
                
            }
        }
    }//GEN-LAST:event_chooseFileButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjectPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjectPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjectPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjectPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjectPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel activeUsersLabel;
    private javax.swing.JButton chooseFileButton;
    private javax.swing.JButton disconnectBtn;
    private javax.swing.JList<String> generalList;
    private javax.swing.JTextField generalMessageFieldTxt;
    private javax.swing.JButton generalSendMessageBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel projectKeyIndicatorLabel;
    private javax.swing.JLabel projectKeyIndicatorLabel1;
    private javax.swing.JLabel projectKeyLabel;
    // End of variables declaration//GEN-END:variables
}
