/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.fsm.client.gui;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.Socket;
import java.nio.charset.Charset;
import java.nio.charset.StandardCharsets;
import java.util.Locale;
import javax.swing.DefaultListModel;


public class ProjectPage extends javax.swing.JFrame{

    private Socket client;
    private DataInputStream in;
    private DataOutputStream out;
    private String key;
    private DefaultListModel<String> model = new DefaultListModel<>();
    
    /**
     * Creates new form ProjectPage
     */
    public ProjectPage() {
        initComponents();
    }
    
    public void initialize(String key, Socket socket, DataInputStream dis, DataOutputStream dos){
        this.client = socket;
        this.in = dis;
        this.out = dos;
        this.key = "A";
        this.projectKeyLabel.setText(key);
        ListenForMessage();
        generalList.setModel(model);
    }
    
    public void ListenForMessage(){
        new Thread(new Runnable() {
            @Override
            public void run() {
                while(true){
                    String response = ReadMessage();
                    
                    String[] parts = response.split("\\$");
                    String command = parts[0];
                    
                    if(command.equals("USERS")){
                        String users = parts[1];
                        activeUsersLabel.setText(users);
                    }
                    
                    if(command.equals("GENERAL")){
                        String msg = parts[1];
                        
                        model.add(model.getSize(), msg);
                    }
                    
                }
            }
        }).start();
    }
    
    private void SendMessage(String msg){
        try {
            byte[] bytes = msg.getBytes(StandardCharsets.UTF_8);
            this.out.write(bytes);  
        } catch (IOException err) {
            
        }
    }
    
    private String ReadMessage(){
        try {
            byte[] messageByte = new byte[1024];
            int bytesRead = in.read(messageByte); 
            return new String(messageByte, 0, bytesRead, Charset.forName("UTF-8")); 
        } catch (IOException | StringIndexOutOfBoundsException err) {
            return "";
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        projectKeyIndicatorLabel = new javax.swing.JLabel();
        projectKeyLabel = new javax.swing.JLabel();
        projectKeyIndicatorLabel1 = new javax.swing.JLabel();
        activeUsersLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        generalList = new javax.swing.JList<>();
        generalMessageFieldTxt = new javax.swing.JTextField();
        generalSendMessageBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        projectKeyIndicatorLabel.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        projectKeyIndicatorLabel.setText("Proje Anahtarı:");

        projectKeyLabel.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        projectKeyLabel.setText("<>");

        projectKeyIndicatorLabel1.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        projectKeyIndicatorLabel1.setText("Aktif Kullanıcılar:");

        activeUsersLabel.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        activeUsersLabel.setText("<>");

        jLabel1.setText("Genel Mesajlaşma");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jScrollPane1.setViewportView(generalList);

        generalSendMessageBtn.setText("Genel Mesaj GÖNDER");
        generalSendMessageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generalSendMessageBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(projectKeyIndicatorLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(projectKeyLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(projectKeyIndicatorLabel1)
                                .addGap(9, 9, 9)
                                .addComponent(activeUsersLabel))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(generalMessageFieldTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(generalSendMessageBtn)))
                .addContainerGap(190, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(projectKeyIndicatorLabel)
                    .addComponent(projectKeyLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(projectKeyIndicatorLabel1)
                    .addComponent(activeUsersLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(generalMessageFieldTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(generalSendMessageBtn)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generalSendMessageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generalSendMessageBtnActionPerformed
        SendMessage("GENERAL$" + "A$" + generalMessageFieldTxt.getText());
        
        generalMessageFieldTxt.setText("");
    }//GEN-LAST:event_generalSendMessageBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjectPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjectPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjectPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjectPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjectPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel activeUsersLabel;
    private javax.swing.JList<String> generalList;
    private javax.swing.JTextField generalMessageFieldTxt;
    private javax.swing.JButton generalSendMessageBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel projectKeyIndicatorLabel;
    private javax.swing.JLabel projectKeyIndicatorLabel1;
    private javax.swing.JLabel projectKeyLabel;
    // End of variables declaration//GEN-END:variables
}
